# coding: utf-8

"""
    Fax.to REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.fax_api import FaxApi


class TestFaxApi(unittest.TestCase):
    """ FaxApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.fax_api.FaxApi()

    def tearDown(self):
        pass

    def test_fax_document_id_costs_get(self):
        """
        Test case for fax_document_id_costs_get

        
        """
        pass

    def test_fax_history_get(self):
        """
        Test case for fax_history_get

        
        """
        pass

    def test_fax_job_id_status_get(self):
        """
        Test case for fax_job_id_status_get

        
        """
        pass

    def test_fax_post(self):
        """
        Test case for fax_post

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
