# coding: utf-8

"""
    Fax.to REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.country_api import CountryApi


class TestCountryApi(unittest.TestCase):
    """ CountryApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.country_api.CountryApi()

    def tearDown(self):
        pass

    def test_areacodes_country_code_state_id_get(self):
        """
        Test case for areacodes_country_code_state_id_get

        
        """
        pass

    def test_countries_country_code_didgroups_get(self):
        """
        Test case for countries_country_code_didgroups_get

        
        """
        pass

    def test_countries_didgroups_did_group_id_provision_post(self):
        """
        Test case for countries_didgroups_did_group_id_provision_post

        
        """
        pass

    def test_countries_get(self):
        """
        Test case for countries_get

        
        """
        pass

    def test_states_country_code_get(self):
        """
        Test case for states_country_code_get

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
