# coding: utf-8

"""
    Fax.to REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.number_api import NumberApi


class TestNumberApi(unittest.TestCase):
    """ NumberApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.number_api.NumberApi()

    def tearDown(self):
        pass

    def test_numbers_get(self):
        """
        Test case for numbers_get

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
