# coding: utf-8

"""
    Fax.to REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.files_api import FilesApi


class TestFilesApi(unittest.TestCase):
    """ FilesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.files_api.FilesApi()

    def tearDown(self):
        pass

    def test_file_clean_get(self):
        """
        Test case for file_clean_get

        
        """
        pass

    def test_file_generate_preview_get(self):
        """
        Test case for file_generate_preview_get

        
        """
        pass

    def test_files_get(self):
        """
        Test case for files_get

        
        """
        pass

    def test_files_id_delete(self):
        """
        Test case for files_id_delete

        
        """
        pass

    def test_files_post(self):
        """
        Test case for files_post

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
