# coding: utf-8

"""
    Fax.to REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """ AccountApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.account_api.AccountApi()

    def tearDown(self):
        pass

    def test_balance_get(self):
        """
        Test case for balance_get

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
